In [29]:
import janitor
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import StandardScaler# escalamiento a los datos para que los valores se ajusten a ello
from sklearn.linear_model import LinearRegression # modelo de regresión lineal

# SVC
Support Vector Machine (SVC) es un algoritmo de aprendizaje automático supervisado que se utiliza para clasificar datos. La SVC funciona encontrando una frontera de decisión que separa los datos de dos clases.

La SVC es útil en las siguientes situaciones:

* Problemas de clasificación lineal o no lineal.
* Espacios de características de alta dimensión: Puede ser eficaz incluso en espacios de características de alta dimensión, como en la clasificación de texto o imágenes.

### Ventajas y desventajas
### Ventajas

1. Efectiva en espacios de características de alta dimensión: Puede manejar eficientemente conjuntos de datos con un gran número de características.
2. Robusto ante espacios de características no lineales.
3. Eficiente en memoria.

### Desventajas

1. sensibilidad a la escala y al ruido.
2. Elección del kernel y parámetros.
3. Dificultad con conjuntos de datos muy grandes.

In [30]:
data = pd.read_csv('../../data/raw/Social_Network_Ads.csv')
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [31]:
categorical_columns = data.select_dtypes(include = 'object').columns
categorical_columns

Index(['Gender'], dtype='object')

In [32]:
import sklearn.preprocessing

In [33]:
import sklearn.compose
import sklearn.preprocessing


transformer = sklearn.compose.make_column_transformer(
    (sklearn.preprocessing.OneHotEncoder(),categorical_columns),
    remainder='passthrough'
)

In [34]:
encoded_df = (
    pd.DataFrame(
        transformer.fit_transform(data),
        columns=transformer.get_feature_names_out(),
        index=data.index
    )
    .rename(
        columns = lambda x:x.removeprefix('onehotencoder__')
    )
    .rename(
        columns = lambda x:x.removeprefix('remainder__')
    )
)

In [35]:
X =encoded_df.iloc[:,[3,4]]
y=encoded_df.iloc[:,-1].values

In [36]:
from sklearn.model_selection import train_test_split

In [37]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)


In [38]:
from sklearn.preprocessing import StandardScaler

import warnings
warnings.filterwarnings('ignore', category=FutureWarning)


In [39]:
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [40]:
from sklearn.svm import SVC

In [41]:
cls = SVC(kernel='linear', random_state=0)
cls.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

In [42]:
y_pred = cls.predict(X_test)

In [43]:
from sklearn.metrics import confusion_matrix


In [44]:
print(confusion_matrix(y_test, y_pred))


[[66  2]
 [ 8 24]]


In [45]:
from sklearn.metrics import precision_score, recall_score


In [46]:
print('Precision:',precision_score(y_test, y_pred))
print('Recall:',recall_score(y_test, y_pred))

Precision: 0.9230769230769231
Recall: 0.75


In [47]:
from sklearn.metrics import f1_score


In [48]:
print('F1:',f1_score(y_test, y_pred))


F1: 0.8275862068965517


In [49]:
cls = SVC(kernel='rbf', random_state=0)
cls.fit(X_train, y_train)
y_pred = cls.predict(X_test)


In [50]:
print(confusion_matrix(y_test, y_pred))
print('Precision:',precision_score(y_test, y_pred))
print('Recall:',recall_score(y_test, y_pred))
print('F1:',f1_score(y_test, y_pred))

[[64  4]
 [ 3 29]]
Precision: 0.8787878787878788
Recall: 0.90625
F1: 0.8923076923076922


In [52]:

cls = SVC(kernel='poly', random_state=0)
cls.fit(X_train, y_train)
y_pred = cls.predict(X_test)


In [53]:
print(confusion_matrix(y_test, y_pred))
print('Precision:',precision_score(y_test, y_pred))
print('Recall:',recall_score(y_test, y_pred))
print('F1:',f1_score(y_test, y_pred))

[[67  1]
 [13 19]]
Precision: 0.95
Recall: 0.59375
F1: 0.7307692307692308
